common:
  run_label: "run_1"
  log_freq: 500
  auto_resume: true
  mixed_precision: true
dataset:
  root_train: "/mnt/imagenet/training"
  root_val: "/mnt/imagenet/validation"
  name: "imagenet"
  category: "classification"
  train_batch_size0: 128
  val_batch_size0: 100
  eval_batch_size0: 100
  workers: 4
  persistent_workers: false
  pin_memory: true
sampler:
  name: "batch_sampler"
  bs:
    crop_size_width: 256
    crop_size_height: 256
model:
  classification:
    name: "mobilevit"
    classifier_dropout: 0.1
    mit:
      mode: "x_small"
      ffn_dropout: 0.0
      attn_dropout: 0.0
      dropout: 0.1
      number_heads: 4
      no_fuse_local_global_features: false
      conv_kernel_size: 3
    activation:
      name: "swish"
    n_classes: 3
  normalization:
    name: "batch_norm_2d"
    momentum: 0.1
  activation:
    name: "swish"
  layer:
    global_pool: "mean"
    conv_init: "kaiming_normal"
    linear_init: "trunc_normal"
    linear_init_std_dev: 0.02
ddp:
  enable: true
  rank: 0
  world_size: -1
  dist_port: 30786
stats:
  name: [ "loss", "top1", "top5" ]
  checkpoint_metric: "top1"
  checkpoint_metric_max: true
